# SPDX-License-Identifier: AGPL-3.0-or-later
name: Secret Scanner

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@8a8ef8526528d8a4ff3e2c90be08e25ef8efbd9b # v3
        with:
          extra_args: --only-verified

      - name: Check for hardcoded emails (should be jonathan.jewell@open.ac.uk)
        run: |
          # Find suspicious email patterns (not the approved email)
          APPROVED_EMAIL="jonathan.jewell@open.ac.uk"
          SUSPICIOUS=$(grep -rE '[a-zA-Z0-9._%+-]+@(example\.com|localhost|placeholder|fake|test\.)' . --include='*.md' --include='*.scm' --include='*.yml' --include='*.yaml' --include='*.json' || true)
          if [ -n "$SUSPICIOUS" ]; then
            echo "::warning::Found potentially fake email addresses. Use $APPROVED_EMAIL instead."
            echo "$SUSPICIOUS"
          fi
